db: biu
server:
  port: 8888
  servlet:
    context-path: /api/v1
    session:
      cookie:
        name: BIUSID
spring:
  profiles:
    active: dev
    include: druid,mybatisplus,shiro
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${db}?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
logging:
  path: ./logs
  level:
    com.abc.dao: debug
imageDir:
  path: E:/testImageForOnlineClass/
